/**
 * Football API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Team } from './team';


export interface Player { 
    id?: number;
    code?: string | null;
    name?: string | null;
    position?: string | null;
    dateOfBirth?: Date | null;
    countryOfBirth?: string | null;
    nationality?: string | null;
    teamId?: number;
    team?: Team;
    teamCode?: string | null;
}

